### ISSUE TITLE
New icons

### ISSUE THREAD

**Issue by davewhitley** [blakeperdue/ios7-wireframe-kit#6]
In iOS 8, some of the icons have been tweaked. Not sure if this is an issue, since the template is based on iOS7. It would be nice to have an iOS8 template.

**Comment by blakeperdue** [comment]
Thanks for noticing. I don't have any immediate plans to update it to iOS 8. There are other iOS 8 templates around the web if you do a google search. Feel free to fork and add icons if you'd like.
